# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "MetadataEditor"
  tags:
  - "internal"
spec:
  type: "website"
  lifecycle: "production"
  owner: "datadeling_og_distribusjon"
  system: "geonorge"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Group"
metadata:
  name: "security_champion_MetadataEditor"
  title: "Security Champion MetadataEditor"
spec:
  type: "security_champion"
  parent: "land_security_champions"
  members:
  - "dagolav"
  children:
  - "resource:MetadataEditor"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Resource"
metadata:
  name: "MetadataEditor"
  links:
  - url: "https://github.com/kartverket/MetadataEditor"
    title: "MetadataEditor på GitHub"
spec:
  type: "repo"
  owner: "security_champion_MetadataEditor"
  dependencyOf:
  - "component:MetadataEditor"
