apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: MetadataEditor
  tags:
    - internal
spec:
  type: website
  lifecycle: production
  owner: group:default/geonorge
  system: system:default/geonorge
