//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kartverket.MetadataEditor.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geonorge - metadataeditor.
        /// </summary>
        public static string AppPageTitle {
            get {
                return ResourceManager.GetString("AppPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre som XML.
        /// </summary>
        public static string Button_SaveAsXml {
            get {
                return ResourceManager.GetString("Button_SaveAsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprettet dato må være på formen dd.mm.yyyy, f.eks. 19.01.2014..
        /// </summary>
        public static string DateCreated_InvalidDate {
            get {
                return ResourceManager.GetString("DateCreated_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rediger metadata.
        /// </summary>
        public static string EditMetadata {
            get {
                return ResourceManager.GetString("EditMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugyldig uuid.
        /// </summary>
        public static string Error_InvalidUuid {
            get {
                return ResourceManager.GetString("Error_InvalidUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} må være en dato på formen 19.01.2014..
        /// </summary>
        public static string FieldMustBeDate {
            get {
                return ResourceManager.GetString("FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} må være et tall..
        /// </summary>
        public static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sammendrag.
        /// </summary>
        public static string Metadata_Abstract {
            get {
                return ResourceManager.GetString("Metadata_Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - Øst - er ikke gyldig. Koordinaten må oppgis med punktum og minst 2 desimaler nøyaktighet..
        /// </summary>
        public static string Metadata_BoundingBox_East_Invalid {
            get {
                return ResourceManager.GetString("Metadata_BoundingBox_East_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - Nord - er ikke gyldig. Koordinaten må oppgis med punktum og minst 2 desimaler nøyaktighet..
        /// </summary>
        public static string Metadata_BoundingBox_North_Invalid {
            get {
                return ResourceManager.GetString("Metadata_BoundingBox_North_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - Sør - er ikke gyldig. Koordinaten må oppgis med punktum og minst 2 desimaler nøyaktighet..
        /// </summary>
        public static string Metadata_BoundingBox_South_Invalid {
            get {
                return ResourceManager.GetString("Metadata_BoundingBox_South_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - Vest - er ikke gyldig. Koordinaten må oppgis med punktum og minst 2 desimaler nøyaktighet..
        /// </summary>
        public static string Metadata_BoundingBox_West_Invalid {
            get {
                return ResourceManager.GetString("Metadata_BoundingBox_West_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epost er påkrevd når navn på kontaktperson er oppgitt..
        /// </summary>
        public static string Metadata_Contact_Email_Required {
            get {
                return ResourceManager.GetString("Metadata_Contact_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadatakontakt er et påkrevd felt..
        /// </summary>
        public static string Metadata_Contact_Name_Required {
            get {
                return ResourceManager.GetString("Metadata_Contact_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjon er påkrevd når navn på kontaktperson er oppgitt..
        /// </summary>
        public static string Metadata_Contact_Organization_Required {
            get {
                return ResourceManager.GetString("Metadata_Contact_Organization_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprettet dato.
        /// </summary>
        public static string Metadata_DateCreated {
            get {
                return ResourceManager.GetString("Metadata_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publiseringsdato.
        /// </summary>
        public static string Metadata_DatePublished {
            get {
                return ResourceManager.GetString("Metadata_DatePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato sist oppdatert.
        /// </summary>
        public static string Metadata_DateUpdated {
            get {
                return ResourceManager.GetString("Metadata_DateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljer om datasett.
        /// </summary>
        public static string Metadata_Edit_DatasetFields {
            get {
                return ResourceManager.GetString("Metadata_Edit_DatasetFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det oppstod en feil under lagring av metadata: {0}..
        /// </summary>
        public static string Metadata_Edit_Saved_Failure {
            get {
                return ResourceManager.GetString("Metadata_Edit_Saved_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadataene ble lagret..
        /// </summary>
        public static string Metadata_Edit_Saved_Success {
            get {
                return ResourceManager.GetString("Metadata_Edit_Saved_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljer om tjeneste.
        /// </summary>
        public static string Metadata_Edit_ServiceFields {
            get {
                return ResourceManager.GetString("Metadata_Edit_ServiceFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenker.
        /// </summary>
        public static string Metadata_Links {
            get {
                return ResourceManager.GetString("Metadata_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjon.
        /// </summary>
        public static string Metadata_Organization {
            get {
                return ResourceManager.GetString("Metadata_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formål.
        /// </summary>
        public static string Metadata_Purpose {
            get {
                return ResourceManager.GetString("Metadata_Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tittel.
        /// </summary>
        public static string Metadata_Title {
            get {
                return ResourceManager.GetString("Metadata_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Metadata_Type {
            get {
                return ResourceManager.GetString("Metadata_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasett.
        /// </summary>
        public static string Metadata_Type_Dataset {
            get {
                return ResourceManager.GetString("Metadata_Type_Dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjeneste.
        /// </summary>
        public static string Metadata_Type_Service {
            get {
                return ResourceManager.GetString("Metadata_Type_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validering.
        /// </summary>
        public static string Metadata_Validation {
            get {
                return ResourceManager.GetString("Metadata_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine metadata.
        /// </summary>
        public static string MyMetadata_Label {
            get {
                return ResourceManager.GetString("MyMetadata_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjon.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdien &apos;{0}&apos; er ikke gyldig for feltet {1}..
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} er et påkrevd felt..
        /// </summary>
        public static string PropertyValueRequired {
            get {
                return ResourceManager.GetString("PropertyValueRequired", resourceCulture);
            }
        }
    }
}
