//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kartverket.MetadataEditor.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til nøkkelord.
        /// </summary>
        public static string AddKeyword {
            get {
                return ResourceManager.GetString("AddKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geonorge - metadataeditor.
        /// </summary>
        public static string AppPageTitle {
            get {
                return ResourceManager.GetString("AppPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til ny distribusjonsløsning.
        /// </summary>
        public static string Button_Add_Distribution {
            get {
                return ResourceManager.GetString("Button_Add_Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjern distribusjonsløsning.
        /// </summary>
        public static string Button_Remove_Distribution {
            get {
                return ResourceManager.GetString("Button_Remove_Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre som XML.
        /// </summary>
        public static string Button_SaveAsXml {
            get {
                return ResourceManager.GetString("Button_SaveAsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publiser.
        /// </summary>
        public static string Button_Validate {
            get {
                return ResourceManager.GetString("Button_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tegneregler.
        /// </summary>
        public static string Cartography {
            get {
                return ResourceManager.GetString("Cartography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begreper.
        /// </summary>
        public static string Concepts {
            get {
                return ResourceManager.GetString("Concepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktperson - Epost.
        /// </summary>
        public static string Contact_Email {
            get {
                return ResourceManager.GetString("Contact_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktperson - Navn.
        /// </summary>
        public static string Contact_Name {
            get {
                return ResourceManager.GetString("Contact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktperson - Organisasjonsnavn.
        /// </summary>
        public static string Contact_Organization {
            get {
                return ResourceManager.GetString("Contact_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt oss.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprett produktark.
        /// </summary>
        public static string CreateProductFactSheet {
            get {
                return ResourceManager.GetString("CreateProductFactSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktside (URL).
        /// </summary>
        public static string DataProductSiteUrl {
            get {
                return ResourceManager.GetString("DataProductSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktspesifikasjon.
        /// </summary>
        public static string DataProductSpecification {
            get {
                return ResourceManager.GetString("DataProductSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn på datasett.
        /// </summary>
        public static string DatasetName {
            get {
                return ResourceManager.GetString("DatasetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprettet dato må være på formen dd.mm.yyyy, f.eks. 19.01.2014..
        /// </summary>
        public static string DateCreated_InvalidDate {
            get {
                return ResourceManager.GetString("DateCreated_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slett.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis i kartkatalogen.
        /// </summary>
        public static string DisplayInMapCatalogue {
            get {
                return ResourceManager.GetString("DisplayInMapCatalogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribusjon.
        /// </summary>
        public static string Distribution {
            get {
                return ResourceManager.GetString("Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribusjonstype.
        /// </summary>
        public static string DistributionType {
            get {
                return ResourceManager.GetString("DistributionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rediger metadata.
        /// </summary>
        public static string EditMetadata {
            get {
                return ResourceManager.GetString("EditMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feil.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugyldig uuid.
        /// </summary>
        public static string Error_InvalidUuid {
            get {
                return ResourceManager.GetString("Error_InvalidUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det har desverre skjedd en feil med din forespørsel. Prøv igjen om litt..
        /// </summary>
        public static string ErrorInfo {
            get {
                return ResourceManager.GetString("ErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Feilen er logget og vil sjekkes av systemansvarlig.&lt;/p&gt;
        ///&lt;p&gt;Du kan også rapportere feilen til &lt;a mailto:&quot;post@norgedigitalt.no&quot;&gt;post@norgedigitalt.no&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string ErrorReport {
            get {
                return ResourceManager.GetString("ErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} må være en dato på formen 19.01.2014..
        /// </summary>
        public static string FieldMustBeDate {
            get {
                return ResourceManager.GetString("FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} må være et tall..
        /// </summary>
        public static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formater.
        /// </summary>
        public static string Formats {
            get {
                return ResourceManager.GetString("Formats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning.
        /// </summary>
        public static string GeographicExtent {
            get {
                return ResourceManager.GetString("GeographicExtent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustrasjonsbilde.
        /// </summary>
        public static string GraphicsOverview {
            get {
                return ResourceManager.GetString("GraphicsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Åpne data&lt;/b&gt;: Data som er åpent tilgjengelig for nedlasting og bruk. (grønn)&amp;nbsp;&lt;b&gt;Norge digital-begrenset&lt;/b&gt;: Data som kun er fritt tilgjengelig for deltakere i Norge digitalt-samarbeidet (gul). &lt;b&gt;Skjermede data&lt;/b&gt;: Data som ikke er tilgjengelige for nedlasting (rød)..
        /// </summary>
        public static string Helptext_AccessConstraints {
            get {
                return ResourceManager.GetString("Helptext_AccessConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv inn koordinatverdier for utstrekning, eller bruk  forhåndsdefinerte områdenavn i nedtrekkslisten dersom de geografiske dataene gjelder for et bestemt fylke eller en kommune. Desimalskille er punktum. Du kan også angi koordinatene ved å bruke knappen &quot;Angi i kartet&quot; for å definere et rektangel i Norgeskart..
        /// </summary>
        public static string Helptext_BoundingBox {
            get {
                return ResourceManager.GetString("Helptext_BoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktpunkt (person eller avdeling) som vedlikeholder metadata og som kan svare på spørsmål knyttet til disse. &quot;Navn&quot; kan referer både til avdelingsnavn, enhet eller personnavn men er ikke påkrevd. Organisasjonsnavn skal skrives med det navnet organisasjonen omtales som eksternt uten henvisninger til avdeling eller underliggende enhet. Epost bør gå til fellesadresse som drift@etat.no.
        /// </summary>
        public static string Helptext_ContactMetadata {
            get {
                return ResourceManager.GetString("Helptext_ContactMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktpunkt (person eller avdeling) som har et eierforhold til datene og kan svare inngående om faglige forhold rundt datasettets struktur og innhold. &quot;Navn&quot; kan referer både til avdelingsnavn, enhet eller personnavn men er ikke påkrevd. Organisasjonsnavn skal skrives med det navnet organisasjonen omtales som eksternt uten henvisninger til avdeling eller underliggende enhet. Epost bør gå til fellesadresse som drift@etat.no.
        /// </summary>
        public static string Helptext_ContactOwner {
            get {
                return ResourceManager.GetString("Helptext_ContactOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktpunkt (person eller avdeling) som kan svare på tekniske detaljer angående publisering og tilgjengeliggjøring av datene. &quot;Navn&quot; kan referer både til avdelingsnavn, enhet eller personnavn men er ikke påkrevd. Organisasjonsnavn skal skrives med det navnet organisasjonen omtales som eksternt uten henvisninger til avdeling eller underliggende enhet. Epost bør gå til fellesadresse som drift@etat.no.
        /// </summary>
        public static string Helptext_ContactPublisher {
            get {
                return ResourceManager.GetString("Helptext_ContactPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flere format kan angis. Versjon av formatet som leveres via filer eller tjenester, for eksempel gml 3.2.1..
        /// </summary>
        public static string Helptext_DistributionsFormats {
            get {
                return ResourceManager.GetString("Helptext_DistributionsFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fylles bare ut for tjenester, og kun hvis metadataene gjelder et enkelt lag eller gruppelag i tjenesten og ikke hele tjenesten..
        /// </summary>
        public static string Helptext_DistributionsFormatsDistributionName {
            get {
                return ResourceManager.GetString("Helptext_DistributionsFormatsDistributionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg riktig distribusjonsform for ressursen (datasette/tjenesten/websiden).
        /// </summary>
        public static string Helptext_DistributionsFormatsProtocol {
            get {
                return ResourceManager.GetString("Helptext_DistributionsFormatsProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fyll inn adresse til nedlastningsside/webside eller tjeneste. For tjenester skal URL angis med lenke til GetCapabilities (service og request på fylles ut)..
        /// </summary>
        public static string Helptext_DistributionsFormatsURL {
            get {
                return ResourceManager.GetString("Helptext_DistributionsFormatsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her må du laste opp stort bilde. Det lages automatisk et miniatyrbilde..
        /// </summary>
        public static string Helptext_Image {
            get {
                return ResourceManager.GetString("Helptext_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvis datasettet inneholder data som inngår blant Inspire-datasettene, skal det refereres til GEMET – Inspire themes, version 1.0 og riktig tema. Det er ingen krav om at datasettet er komplett i henhold til en Inspire datasettspesifikasjon. (Egen kodeliste)..
        /// </summary>
        public static string Helptext_KeywordsInspire {
            get {
                return ResourceManager.GetString("Helptext_KeywordsInspire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nøkkelordliste som viser til lover eller regler datasettet/serien er omfattet av eller forpliktende samarbeid som datasettet/serien inngår i. (Egen kodeliste).
        /// </summary>
        public static string Helptext_KeywordsNationalInitiative {
            get {
                return ResourceManager.GetString("Helptext_KeywordsNationalInitiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En norsk tematisk inndeling basert på kategoriene fra det offentlige kartgrunnlaget..
        /// </summary>
        public static string Helptext_KeywordsNationalTheme {
            get {
                return ResourceManager.GetString("Helptext_KeywordsNationalTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne nøkkelordtypen skal helst ikke brukes, men her vises nøkkelord som ikke er spesifisert å tilhøre en spesifikk nøkkelordkategori. Det anbefales at nøkkelord fjernes fra denne kategorien og legges inn under riktig kategori..
        /// </summary>
        public static string Helptext_KeywordsOther {
            get {
                return ResourceManager.GetString("Helptext_KeywordsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det kan for eksempel være kommunenavn for kommunale datasett, eller Norges fastland for landsdekkende datasett. Skriv steder datasettet dekker i stedet for hva det ikke dekker..
        /// </summary>
        public static string Helptext_KeywordsPlace {
            get {
                return ResourceManager.GetString("Helptext_KeywordsPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gode nøkkelord er en forutsetning for at metadataene skal bli funnet av brukerne. Nøkkelord skal skrives i entall og det skal brukes folkelige termer i tillegg til mer spesifikke faguttrykk. Både overordnede metadata og mer detaljerte metadata, helt ned på objektnivå bør vurderes..
        /// </summary>
        public static string Helptext_KeywordsTheme {
            get {
                return ResourceManager.GetString("Helptext_KeywordsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisens for datasettet/datatjenesten..
        /// </summary>
        public static string Helptext_LicenseTypes {
            get {
                return ResourceManager.GetString("Helptext_LicenseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For tjenester som omfattes av Norge digitalt-avtalen skal tjenesteerklæring i henhold til avtalens &quot;generelle vilkår&quot; oppgis..
        /// </summary>
        public static string Helptext_OrderingInstructions {
            get {
                return ResourceManager.GetString("Helptext_OrderingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataprodusentens generelle kunnskap om opprinnelsen og prosesshistorien til et datasett eller tjeneste. Forklar kort hvilke vikte operasjoner som er gjort fra datafangst til leveranse, og hvordan dette eventuelt påvirker kvalitet og innhold i datasettet.
        /// </summary>
        public static string Helptext_ProcessHistory {
            get {
                return ResourceManager.GetString("Helptext_ProcessHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Målestokkstallet skal legges inn som et heltall (eks: 5000).
        /// </summary>
        public static string Helptext_ResolutionScale {
            get {
                return ResourceManager.GetString("Helptext_ResolutionScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikkerhetsnivå på datasettet/datatjenesten..
        /// </summary>
        public static string Helptext_SecurityConstraints {
            get {
                return ResourceManager.GetString("Helptext_SecurityConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grunngiving av tilgangsbegrensninger eller bruksbegrensninger i form av juridiske forhold eller andre begrensende faktorer. Her kan en henvise til lov, forskrift eller lignende..
        /// </summary>
        public static string Helptext_SecurityConstraintsNote {
            get {
                return ResourceManager.GetString("Helptext_SecurityConstraintsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status for datasett eller datasett tjenesten opererer mot..
        /// </summary>
        public static string Helptext_Status {
            get {
                return ResourceManager.GetString("Helptext_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tematisk inndeling definert i metadatastandarden..
        /// </summary>
        public static string Helptext_TopicCategory {
            get {
                return ResourceManager.GetString("Helptext_TopicCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krav som må være oppfylt for å anvende datasettet/tjenesten..
        /// </summary>
        public static string Helptext_UseConstraints {
            get {
                return ResourceManager.GetString("Helptext_UseConstraints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angir hvilke områder dataene ikke er egnet for. F.eks &quot;dataene er ikke egnet for kommunens arealplanarbeide&quot; eller &quot;må ikke brukes til å navigere etter&quot;. En bør også oppgi hvorfor det er begrensninger på bruk..
        /// </summary>
        public static string Helptext_UseLimitations {
            get {
                return ResourceManager.GetString("Helptext_UseLimitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL til hjelp.
        /// </summary>
        public static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forside.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle.
        /// </summary>
        public static string Language_All {
            get {
                return ResourceManager.GetString("Language_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engelsk.
        /// </summary>
        public static string Language_En {
            get {
                return ResourceManager.GetString("Language_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norsk.
        /// </summary>
        public static string Language_No {
            get {
                return ResourceManager.GetString("Language_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivelse.
        /// </summary>
        public static string Metadata_Abstract {
            get {
                return ResourceManager.GetString("Metadata_Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilgangsrestriksjoner.
        /// </summary>
        public static string Metadata_AccessConstraints_Label {
            get {
                return ResourceManager.GetString("Metadata_AccessConstraints_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arealplaner underlagt Pbl.
        /// </summary>
        public static string Metadata_Admin_KeywordArealPlans {
            get {
                return ResourceManager.GetString("Metadata_Admin_KeywordArealPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOK i henhold til KMD-definisjon.
        /// </summary>
        public static string Metadata_Admin_KeywordDokValidKmd {
            get {
                return ResourceManager.GetString("Metadata_Admin_KeywordDokValidKmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underlagt Geodataloven.
        /// </summary>
        public static string Metadata_Admin_KeywordGeodatalaw {
            get {
                return ResourceManager.GetString("Metadata_Admin_KeywordGeodatalaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspire i henhold rapportering.
        /// </summary>
        public static string Metadata_Admin_KeywordInspireValid {
            get {
                return ResourceManager.GetString("Metadata_Admin_KeywordInspireValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norge digitalt-avtale.
        /// </summary>
        public static string Metadata_Admin_KeywordNorgeDigitalt {
            get {
                return ResourceManager.GetString("Metadata_Admin_KeywordNorgeDigitalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Høsting til ulike samarbeid:.
        /// </summary>
        public static string Metadata_Admin_KeywordsCatalogs {
            get {
                return ResourceManager.GetString("Metadata_Admin_KeywordsCatalogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato.
        /// </summary>
        public static string Metadata_Admin_QualitySpecificationDate {
            get {
                return ResourceManager.GetString("Metadata_Admin_QualitySpecificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataene er produsert iht produktspesifikasjonen.
        /// </summary>
        public static string Metadata_Admin_QualitySpecificationDate_Conform {
            get {
                return ResourceManager.GetString("Metadata_Admin_QualitySpecificationDate_Conform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataene avviker fra produktspesifikasjonen.
        /// </summary>
        public static string Metadata_Admin_QualitySpecificationDate_NotConform {
            get {
                return ResourceManager.GetString("Metadata_Admin_QualitySpecificationDate_NotConform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avvik fra produktspesifikasjonen.
        /// </summary>
        public static string Metadata_Admin_QualitySpecificationExplanation {
            get {
                return ResourceManager.GetString("Metadata_Admin_QualitySpecificationExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datakonformitet.
        /// </summary>
        public static string Metadata_Admin_QualitySpecificationResult {
            get {
                return ResourceManager.GetString("Metadata_Admin_QualitySpecificationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angitt produktspesifikasjon.
        /// </summary>
        public static string Metadata_Admin_QualitySpecificationTitle {
            get {
                return ResourceManager.GetString("Metadata_Admin_QualitySpecificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - Øst - er ikke gyldig. Koordinaten må oppgis med tall og evt punktum som desimaltegn..
        /// </summary>
        public static string Metadata_BoundingBox_East_Invalid {
            get {
                return ResourceManager.GetString("Metadata_BoundingBox_East_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - Nord - er ikke gyldig. Koordinaten må oppgis med tall og evt punktum som desimaltegn..
        /// </summary>
        public static string Metadata_BoundingBox_North_Invalid {
            get {
                return ResourceManager.GetString("Metadata_BoundingBox_North_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - Sør - er ikke gyldig. Koordinaten må oppgis med tall og evt punktum som desimaltegn..
        /// </summary>
        public static string Metadata_BoundingBox_South_Invalid {
            get {
                return ResourceManager.GetString("Metadata_BoundingBox_South_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - Vest - er ikke gyldig. Koordinaten må oppgis med tall og evt punktum som desimaltegn..
        /// </summary>
        public static string Metadata_BoundingBox_West_Invalid {
            get {
                return ResourceManager.GetString("Metadata_BoundingBox_West_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epost.
        /// </summary>
        public static string Metadata_Contact_Email {
            get {
                return ResourceManager.GetString("Metadata_Contact_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epost til kontaktperson er påkrevd..
        /// </summary>
        public static string Metadata_Contact_Email_Required {
            get {
                return ResourceManager.GetString("Metadata_Contact_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        public static string Metadata_Contact_Name {
            get {
                return ResourceManager.GetString("Metadata_Contact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn på kontaktperson er påkrevd..
        /// </summary>
        public static string Metadata_Contact_Name_Required {
            get {
                return ResourceManager.GetString("Metadata_Contact_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjon.
        /// </summary>
        public static string Metadata_Contact_Organization {
            get {
                return ResourceManager.GetString("Metadata_Contact_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjonsnavn er feil..
        /// </summary>
        public static string Metadata_Contact_Organization_Required {
            get {
                return ResourceManager.GetString("Metadata_Contact_Organization_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angi bildefil.
        /// </summary>
        public static string Metadata_CoverageImage_Image {
            get {
                return ResourceManager.GetString("Metadata_CoverageImage_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg fil.
        /// </summary>
        public static string Metadata_CoverageImage_Select {
            get {
                return ResourceManager.GetString("Metadata_CoverageImage_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last opp.
        /// </summary>
        public static string Metadata_CoverageImage_Upload {
            get {
                return ResourceManager.GetString("Metadata_CoverageImage_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartlagsnavn.
        /// </summary>
        public static string Metadata_CoverageServiceMap_Layer {
            get {
                return ResourceManager.GetString("Metadata_CoverageServiceMap_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjenestetype.
        /// </summary>
        public static string Metadata_CoverageServiceMap_Type {
            get {
                return ResourceManager.GetString("Metadata_CoverageServiceMap_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TjenesteURL.
        /// </summary>
        public static string Metadata_CoverageServiceMap_Url {
            get {
                return ResourceManager.GetString("Metadata_CoverageServiceMap_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type dekningskart.
        /// </summary>
        public static string Metadata_CoverageType {
            get {
                return ResourceManager.GetString("Metadata_CoverageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildefil.
        /// </summary>
        public static string Metadata_CoverageType_ImageCoverage {
            get {
                return ResourceManager.GetString("Metadata_CoverageType_ImageCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karttjenestelag.
        /// </summary>
        public static string Metadata_CoverageType_Mapservice {
            get {
                return ResourceManager.GetString("Metadata_CoverageType_Mapservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webside.
        /// </summary>
        public static string Metadata_CoverageType_Webpage {
            get {
                return ResourceManager.GetString("Metadata_CoverageType_Webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webside.
        /// </summary>
        public static string Metadata_CoverageWebsite_Url {
            get {
                return ResourceManager.GetString("Metadata_CoverageWebsite_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprettet dato.
        /// </summary>
        public static string Metadata_DateCreated {
            get {
                return ResourceManager.GetString("Metadata_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyldig fra dato.
        /// </summary>
        public static string Metadata_DateMetadataValidFrom {
            get {
                return ResourceManager.GetString("Metadata_DateMetadataValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyldig til dato.
        /// </summary>
        public static string Metadata_DateMetadataValidTo {
            get {
                return ResourceManager.GetString("Metadata_DateMetadataValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publiseringsdato.
        /// </summary>
        public static string Metadata_DatePublished {
            get {
                return ResourceManager.GetString("Metadata_DatePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato sist oppdatert.
        /// </summary>
        public static string Metadata_DateUpdated {
            get {
                return ResourceManager.GetString("Metadata_DateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljer om datasett.
        /// </summary>
        public static string Metadata_Edit_DatasetFields {
            get {
                return ResourceManager.GetString("Metadata_Edit_DatasetFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det oppstod en feil under lagring av metadata: {0}..
        /// </summary>
        public static string Metadata_Edit_Saved_Failure {
            get {
                return ResourceManager.GetString("Metadata_Edit_Saved_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadataene ble lagret..
        /// </summary>
        public static string Metadata_Edit_Saved_Success {
            get {
                return ResourceManager.GetString("Metadata_Edit_Saved_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljer om tjeneste.
        /// </summary>
        public static string Metadata_Edit_ServiceFields {
            get {
                return ResourceManager.GetString("Metadata_Edit_ServiceFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspire-kategorier.
        /// </summary>
        public static string Metadata_KeywordsInspire_Label {
            get {
                return ResourceManager.GetString("Metadata_KeywordsInspire_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samarbeid og lover.
        /// </summary>
        public static string Metadata_KeywordsNationalInitiative_Label {
            get {
                return ResourceManager.GetString("Metadata_KeywordsNationalInitiative_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasjonal temakategori.
        /// </summary>
        public static string Metadata_KeywordsNationalTheme_Label {
            get {
                return ResourceManager.GetString("Metadata_KeywordsNationalTheme_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukategoriserte nøkkelord.
        /// </summary>
        public static string Metadata_KeywordsOther_Label {
            get {
                return ResourceManager.GetString("Metadata_KeywordsOther_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nøkkelord for geografisk område.
        /// </summary>
        public static string Metadata_KeywordsPlace_Label {
            get {
                return ResourceManager.GetString("Metadata_KeywordsPlace_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string Metadata_KeywordsTheme_Label {
            get {
                return ResourceManager.GetString("Metadata_KeywordsTheme_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lisens.
        /// </summary>
        public static string Metadata_LicenseTypes_Label {
            get {
                return ResourceManager.GetString("Metadata_LicenseTypes_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenker.
        /// </summary>
        public static string Metadata_Links {
            get {
                return ResourceManager.GetString("Metadata_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppdateringshyppighet.
        /// </summary>
        public static string Metadata_MaintenanceFrequency {
            get {
                return ResourceManager.GetString("Metadata_MaintenanceFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjenesteerklæring.
        /// </summary>
        public static string Metadata_OrderingInstructions_Label {
            get {
                return ResourceManager.GetString("Metadata_OrderingInstructions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjon.
        /// </summary>
        public static string Metadata_Organization {
            get {
                return ResourceManager.GetString("Metadata_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andre restriksjoner.
        /// </summary>
        public static string Metadata_OtherConstraints_Label {
            get {
                return ResourceManager.GetString("Metadata_OtherConstraints_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Metadata_OtherConstraintsLink_Label {
            get {
                return ResourceManager.GetString("Metadata_OtherConstraintsLink_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valgt lisens.
        /// </summary>
        public static string Metadata_OtherConstraintsLinkText_Label {
            get {
                return ResourceManager.GetString("Metadata_OtherConstraintsLinkText_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosesshistorie.
        /// </summary>
        public static string Metadata_ProcessHistory_Label {
            get {
                return ResourceManager.GetString("Metadata_ProcessHistory_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formål.
        /// </summary>
        public static string Metadata_Purpose {
            get {
                return ResourceManager.GetString("Metadata_Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forklaring av resultat.
        /// </summary>
        public static string Metadata_QualitySpecificationExplanation {
            get {
                return ResourceManager.GetString("Metadata_QualitySpecificationExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Målestokkstall.
        /// </summary>
        public static string Metadata_ResolutionScale_Label {
            get {
                return ResourceManager.GetString("Metadata_ResolutionScale_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikkerhetsnivå.
        /// </summary>
        public static string Metadata_SecurityConstraints_Label {
            get {
                return ResourceManager.GetString("Metadata_SecurityConstraints_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lovhenvisning.
        /// </summary>
        public static string Metadata_SecurityConstraintsNote_Label {
            get {
                return ResourceManager.GetString("Metadata_SecurityConstraintsNote_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Metadata_Status {
            get {
                return ResourceManager.GetString("Metadata_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Metadata_Status_Label {
            get {
                return ResourceManager.GetString("Metadata_Status_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata tittel.
        /// </summary>
        public static string Metadata_Title {
            get {
                return ResourceManager.GetString("Metadata_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tematisk hovedkategori.
        /// </summary>
        public static string Metadata_TopicCategory_Label {
            get {
                return ResourceManager.GetString("Metadata_TopicCategory_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Metadata_Type {
            get {
                return ResourceManager.GetString("Metadata_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasett.
        /// </summary>
        public static string Metadata_Type_Dataset {
            get {
                return ResourceManager.GetString("Metadata_Type_Dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjeneste.
        /// </summary>
        public static string Metadata_Type_Service {
            get {
                return ResourceManager.GetString("Metadata_Type_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brukerrestriksjoner.
        /// </summary>
        public static string Metadata_UseConstraints_Label {
            get {
                return ResourceManager.GetString("Metadata_UseConstraints_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruksbegrensninger.
        /// </summary>
        public static string Metadata_UseLimitations_Label {
            get {
                return ResourceManager.GetString("Metadata_UseLimitations_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feil ved validering: {0}..
        /// </summary>
        public static string Metadata_Validate_Error {
            get {
                return ResourceManager.GetString("Metadata_Validate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata ble validert.
        /// </summary>
        public static string Metadata_Validate_Success {
            get {
                return ResourceManager.GetString("Metadata_Validate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validering.
        /// </summary>
        public static string Metadata_Validation {
            get {
                return ResourceManager.GetString("Metadata_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadatakontakt.
        /// </summary>
        public static string MetadataContact {
            get {
                return ResourceManager.GetString("MetadataContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine metadata.
        /// </summary>
        public static string MyMetadata_Label {
            get {
                return ResourceManager.GetString("MyMetadata_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navnerom til datasett.
        /// </summary>
        public static string NamespaceToDataset {
            get {
                return ResourceManager.GetString("NamespaceToDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi finner ikke siden du leter etter, men Geonorge skal hjelpe deg videre..
        /// </summary>
        public static string NotFoundText {
            get {
                return ResourceManager.GetString("NotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjon.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eller angi koordinater.
        /// </summary>
        public static string OrSpecifyCoordinates {
            get {
                return ResourceManager.GetString("OrSpecifyCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annen produktspesifikasjon.
        /// </summary>
        public static string OtherDataProductSpecification {
            get {
                return ResourceManager.GetString("OtherDataProductSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faglig kontakt.
        /// </summary>
        public static string OwnerContact {
            get {
                return ResourceManager.GetString("OwnerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produktark.
        /// </summary>
        public static string ProductFactSheet {
            get {
                return ResourceManager.GetString("ProductFactSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdien &apos;{0}&apos; er ikke gyldig for feltet {1}..
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} er et påkrevd felt..
        /// </summary>
        public static string PropertyValueRequired {
            get {
                return ResourceManager.GetString("PropertyValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknisk kontakt.
        /// </summary>
        public static string PublisherContact {
            get {
                return ResourceManager.GetString("PublisherContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn på datasett.
        /// </summary>
        public static string SimpleMetadata_Title {
            get {
                return ResourceManager.GetString("SimpleMetadata_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representasjonsform.
        /// </summary>
        public static string SpatialRepresentationType {
            get {
                return ResourceManager.GetString("SpatialRepresentationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angi områder.
        /// </summary>
        public static string SpecifyAreas {
            get {
                return ResourceManager.GetString("SpecifyAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angi dekningskart.
        /// </summary>
        public static string SpecifyCoverageMap {
            get {
                return ResourceManager.GetString("SpecifyCoverageMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angi bildefil.
        /// </summary>
        public static string SpecifyImageFile {
            get {
                return ResourceManager.GetString("SpecifyImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrativt.
        /// </summary>
        public static string TabAdministrative {
            get {
                return ResourceManager.GetString("TabAdministrative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grunnleggende.
        /// </summary>
        public static string TabBasicInformation {
            get {
                return ResourceManager.GetString("TabBasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktinformasjon.
        /// </summary>
        public static string TabContactInformation {
            get {
                return ResourceManager.GetString("TabContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribusjon.
        /// </summary>
        public static string TabDistribution {
            get {
                return ResourceManager.GetString("TabDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumentasjon.
        /// </summary>
        public static string TabDocumentation {
            get {
                return ResourceManager.GetString("TabDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nøkkelord.
        /// </summary>
        public static string TabKeywords {
            get {
                return ResourceManager.GetString("TabKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvalitet.
        /// </summary>
        public static string TabQuality {
            get {
                return ResourceManager.GetString("TabQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restriksjoner.
        /// </summary>
        public static string TabRestrictions {
            get {
                return ResourceManager.GetString("TabRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tid og rom.
        /// </summary>
        public static string TabTimeAndSpace {
            get {
                return ResourceManager.GetString("TabTimeAndSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tematisk hovedkategori.
        /// </summary>
        public static string TopicCategory {
            get {
                return ResourceManager.GetString("TopicCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UML-modell.
        /// </summary>
        public static string UMLmodel {
            get {
                return ResourceManager.GetString("UMLmodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk distribusjonsinndeling.
        /// </summary>
        public static string UnitsOfDistribution {
            get {
                return ResourceManager.GetString("UnitsOfDistribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruksområde.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versjon.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
