//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kartverket.MetadataEditor.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geonorge - metadataeditor.
        /// </summary>
        public static string AppPageTitle {
            get {
                return ResourceManager.GetString("AppPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til ny distribusjonsløsning.
        /// </summary>
        public static string Button_Add_Distribution {
            get {
                return ResourceManager.GetString("Button_Add_Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjern distribusjonsløsning.
        /// </summary>
        public static string Button_Remove_Distribution {
            get {
                return ResourceManager.GetString("Button_Remove_Distribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre som XML.
        /// </summary>
        public static string Button_SaveAsXml {
            get {
                return ResourceManager.GetString("Button_SaveAsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publiser.
        /// </summary>
        public static string Button_Validate {
            get {
                return ResourceManager.GetString("Button_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktperson - Epost.
        /// </summary>
        public static string Contact_Email {
            get {
                return ResourceManager.GetString("Contact_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktperson - Navn.
        /// </summary>
        public static string Contact_Name {
            get {
                return ResourceManager.GetString("Contact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktperson - Organisasjonsnavn.
        /// </summary>
        public static string Contact_Organization {
            get {
                return ResourceManager.GetString("Contact_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt oss.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprettet dato må være på formen dd.mm.yyyy, f.eks. 19.01.2014..
        /// </summary>
        public static string DateCreated_InvalidDate {
            get {
                return ResourceManager.GetString("DateCreated_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rediger metadata.
        /// </summary>
        public static string EditMetadata {
            get {
                return ResourceManager.GetString("EditMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feil.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugyldig uuid.
        /// </summary>
        public static string Error_InvalidUuid {
            get {
                return ResourceManager.GetString("Error_InvalidUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det har desverre skjedd en feil med din forespørsel. Prøv igjen om litt..
        /// </summary>
        public static string ErrorInfo {
            get {
                return ResourceManager.GetString("ErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Feilen er logget og vil sjekkes av systemansvarlig.&lt;/p&gt;
        ///&lt;p&gt;Du kan også rapportere feilen til &lt;a mailto:&quot;post@norgedigitalt.no&quot;&gt;post@norgedigitalt.no&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        public static string ErrorReport {
            get {
                return ResourceManager.GetString("ErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} må være en dato på formen 19.01.2014..
        /// </summary>
        public static string FieldMustBeDate {
            get {
                return ResourceManager.GetString("FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} må være et tall..
        /// </summary>
        public static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv inn koordinatverdier for utstrekning, eller bruk  forhåndsdefinerte områdenavn i nedtrekkslisten dersom de geografiske dataene gjelder for et bestemt fylke eller en kommune. Desimalskille er punktum. Du kan også angi koordinatene ved å bruke knappen &quot;Angi i kartet&quot; for å definere et rektangel i Norgeskart..
        /// </summary>
        public static string Helptext_BoundingBox {
            get {
                return ResourceManager.GetString("Helptext_BoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktpunkt (person eller avdeling) som vedlikeholder metadata og som kan svare på spørsmål knyttet til disse. &quot;Navn&quot; kan referer både til avdelingsnavn, enhet eller personnavn men er ikke påkrevd. Organisasjonsnavn skal skrives med det navnet organisasjonen omtales som eksternt uten henvisninger til avdeling eller underliggende enhet. Epost bør gå til fellesadresse som drift@etat.no.
        /// </summary>
        public static string Helptext_ContactMetadata {
            get {
                return ResourceManager.GetString("Helptext_ContactMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktpunkt (person eller avdeling) som har et eierforhold til datene og kan svare inngående om faglige forhold rundt datasettets struktur og innhold. &quot;Navn&quot; kan referer både til avdelingsnavn, enhet eller personnavn men er ikke påkrevd. Organisasjonsnavn skal skrives med det navnet organisasjonen omtales som eksternt uten henvisninger til avdeling eller underliggende enhet. Epost bør gå til fellesadresse som drift@etat.no.
        /// </summary>
        public static string Helptext_ContactOwner {
            get {
                return ResourceManager.GetString("Helptext_ContactOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktpunkt (person eller avdeling) som kan svare på tekniske detaljer angående publisering og tilgjengeliggjøring av datene. &quot;Navn&quot; kan referer både til avdelingsnavn, enhet eller personnavn men er ikke påkrevd. Organisasjonsnavn skal skrives med det navnet organisasjonen omtales som eksternt uten henvisninger til avdeling eller underliggende enhet. Epost bør gå til fellesadresse som drift@etat.no.
        /// </summary>
        public static string Helptext_ContactPublisher {
            get {
                return ResourceManager.GetString("Helptext_ContactPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her må du laste opp stort bilde. Det lages automatisk et miniatyrbilde..
        /// </summary>
        public static string Helptext_Image {
            get {
                return ResourceManager.GetString("Helptext_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forside.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle.
        /// </summary>
        public static string Language_All {
            get {
                return ResourceManager.GetString("Language_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engelsk.
        /// </summary>
        public static string Language_En {
            get {
                return ResourceManager.GetString("Language_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norsk.
        /// </summary>
        public static string Language_No {
            get {
                return ResourceManager.GetString("Language_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivelse.
        /// </summary>
        public static string Metadata_Abstract {
            get {
                return ResourceManager.GetString("Metadata_Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - Øst - er ikke gyldig. Koordinaten må oppgis med tall og evt punktum som desimaltegn..
        /// </summary>
        public static string Metadata_BoundingBox_East_Invalid {
            get {
                return ResourceManager.GetString("Metadata_BoundingBox_East_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - Nord - er ikke gyldig. Koordinaten må oppgis med tall og evt punktum som desimaltegn..
        /// </summary>
        public static string Metadata_BoundingBox_North_Invalid {
            get {
                return ResourceManager.GetString("Metadata_BoundingBox_North_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - Sør - er ikke gyldig. Koordinaten må oppgis med tall og evt punktum som desimaltegn..
        /// </summary>
        public static string Metadata_BoundingBox_South_Invalid {
            get {
                return ResourceManager.GetString("Metadata_BoundingBox_South_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geografisk utstrekning - Vest - er ikke gyldig. Koordinaten må oppgis med tall og evt punktum som desimaltegn..
        /// </summary>
        public static string Metadata_BoundingBox_West_Invalid {
            get {
                return ResourceManager.GetString("Metadata_BoundingBox_West_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epost til kontaktperson er påkrevd..
        /// </summary>
        public static string Metadata_Contact_Email_Required {
            get {
                return ResourceManager.GetString("Metadata_Contact_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn på kontaktperson er påkrevd..
        /// </summary>
        public static string Metadata_Contact_Name_Required {
            get {
                return ResourceManager.GetString("Metadata_Contact_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjonsnavn er feil..
        /// </summary>
        public static string Metadata_Contact_Organization_Required {
            get {
                return ResourceManager.GetString("Metadata_Contact_Organization_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprettet dato.
        /// </summary>
        public static string Metadata_DateCreated {
            get {
                return ResourceManager.GetString("Metadata_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyldig fra dato.
        /// </summary>
        public static string Metadata_DateMetadataValidFrom {
            get {
                return ResourceManager.GetString("Metadata_DateMetadataValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyldig til dato.
        /// </summary>
        public static string Metadata_DateMetadataValidTo {
            get {
                return ResourceManager.GetString("Metadata_DateMetadataValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publiseringsdato.
        /// </summary>
        public static string Metadata_DatePublished {
            get {
                return ResourceManager.GetString("Metadata_DatePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato sist oppdatert.
        /// </summary>
        public static string Metadata_DateUpdated {
            get {
                return ResourceManager.GetString("Metadata_DateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljer om datasett.
        /// </summary>
        public static string Metadata_Edit_DatasetFields {
            get {
                return ResourceManager.GetString("Metadata_Edit_DatasetFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det oppstod en feil under lagring av metadata: {0}..
        /// </summary>
        public static string Metadata_Edit_Saved_Failure {
            get {
                return ResourceManager.GetString("Metadata_Edit_Saved_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadataene ble lagret..
        /// </summary>
        public static string Metadata_Edit_Saved_Success {
            get {
                return ResourceManager.GetString("Metadata_Edit_Saved_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljer om tjeneste.
        /// </summary>
        public static string Metadata_Edit_ServiceFields {
            get {
                return ResourceManager.GetString("Metadata_Edit_ServiceFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenker.
        /// </summary>
        public static string Metadata_Links {
            get {
                return ResourceManager.GetString("Metadata_Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppdateringshyppighet.
        /// </summary>
        public static string Metadata_MaintenanceFrequency {
            get {
                return ResourceManager.GetString("Metadata_MaintenanceFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nasjonal temakategori.
        /// </summary>
        public static string Metadata_NationalTheme_Label {
            get {
                return ResourceManager.GetString("Metadata_NationalTheme_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjon.
        /// </summary>
        public static string Metadata_Organization {
            get {
                return ResourceManager.GetString("Metadata_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formål.
        /// </summary>
        public static string Metadata_Purpose {
            get {
                return ResourceManager.GetString("Metadata_Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forklaring av resultat.
        /// </summary>
        public static string Metadata_QualitySpecificationExplanation {
            get {
                return ResourceManager.GetString("Metadata_QualitySpecificationExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Metadata_Status {
            get {
                return ResourceManager.GetString("Metadata_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata tittel.
        /// </summary>
        public static string Metadata_Title {
            get {
                return ResourceManager.GetString("Metadata_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Metadata_Type {
            get {
                return ResourceManager.GetString("Metadata_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasett.
        /// </summary>
        public static string Metadata_Type_Dataset {
            get {
                return ResourceManager.GetString("Metadata_Type_Dataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tjeneste.
        /// </summary>
        public static string Metadata_Type_Service {
            get {
                return ResourceManager.GetString("Metadata_Type_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feil ved validering: {0}..
        /// </summary>
        public static string Metadata_Validate_Error {
            get {
                return ResourceManager.GetString("Metadata_Validate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata ble validert.
        /// </summary>
        public static string Metadata_Validate_Success {
            get {
                return ResourceManager.GetString("Metadata_Validate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validering.
        /// </summary>
        public static string Metadata_Validation {
            get {
                return ResourceManager.GetString("Metadata_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine metadata.
        /// </summary>
        public static string MyMetadata_Label {
            get {
                return ResourceManager.GetString("MyMetadata_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi finner ikke siden du leter etter, men Geonorge skal hjelpe deg videre..
        /// </summary>
        public static string NotFoundText {
            get {
                return ResourceManager.GetString("NotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisasjon.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdien &apos;{0}&apos; er ikke gyldig for feltet {1}..
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} er et påkrevd felt..
        /// </summary>
        public static string PropertyValueRequired {
            get {
                return ResourceManager.GetString("PropertyValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn på datasett.
        /// </summary>
        public static string SimpleMetadata_Title {
            get {
                return ResourceManager.GetString("SimpleMetadata_Title", resourceCulture);
            }
        }
    }
}
